### ISSUE TITLE
Fetch character information with name

### ISSUE THREAD

**Issue by sireeshdevaraj** [hummingbird-me/api-docs#104]
Hey, I fiddled with the docs a little but couldn't find this, is there a way to get the character information with character name than using ID?. currently it supports anime filtering search. 
This is more like a feature request to add character search.

**Comment by wopian** [comment]
Filter by slug or name is supported (https://kitsu.docs.apiary.io/#reference/characters/characters/fetch-collection)

E.g https://kitsu.io/api/edge/characters?filter[name]=Jet%20Black

**Comment by sireeshdevaraj** [comment]
also, does the API support filtering using `malId` for characters?

**Comment by wopian** [comment]
The JSON:API one these docs are for does not. I'm unsure if the GraphQL API supports that or not though.

**Comment by sireeshdevaraj** [comment]
Can this be added as a feature request?
Filtering out a wanted character name takes time from all the similar names.it makes things easy with MAL
