### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#11]
### Data Structure

- [x] Blocks
- [x] Favorites
- [x] Follows
- [x] Linked Accounts
- [x] Profile Link Sites
- [x] Profile Links
- [x] Roles
- [x] Stats
- [x] User Roles
- [x] Users

#### GET

- [x] Blocks
- [x] Favorites
- [x] Follows
- [x] Linked Accounts
- [x] Profile Link Sites
- [x] Profile Links
- [x] Roles
- [x] Stats
- [x] User Roles
- [x] Users

#### POST

- [x] Blocks
- [x] Favorites
- [x] Follows
- [x] Linked Accounts
- [x] Profile Links
- [x] Users

#### PATCH

- [x] Favorites
- [x] Linked Accounts
- [x] Profile Links
- [x] Users

#### DELETE

- [x] Blocks
- [x] Favorites
- [x] Follows
- [x] Linked Accounts
- [x] Profile Links
- [x] Users

### Documented & Explained

- [x] Blocks
- [x] Favorites
- [x] Follows
- [x] Linked Accounts
- [x] Profile Link Sites
- [x] Profile Links
- [x] Roles
- [x] Stats
- [x] User Roles
- [x] Users

**Comment by JasonLighthunter** [comment]
will begin to work on favorites

**Comment by JasonLighthunter** [comment]
will begin to work on follows

**Comment by JasonLighthunter** [comment]
will work on profile link sites

**Comment by JasonLighthunter** [comment]
will begin to work on profileLinks

**Comment by JasonLighthunter** [comment]
will begin to work on roles

**Comment by JasonLighthunter** [comment]
will begin to work on user Roles

**Comment by JasonLighthunter** [comment]
will begin to work on user

**Comment by wopian** [comment]
Doing stats
