### ISSUE TITLE
User Libraries

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#26]
### Data Structure

- [x] Library Entries
- [x] Library Entry Logs
- [x] Library Events
- [x] List Imports

#### GET

- [x] Library Entries
- [x] Library Entry Logs
- [x] Library Events
- [x] List Imports

#### POST

- [x] Library Entries
- [x] List Imports

#### PATCH

- [x] Library Entries

#### DELETE

- [x] Library Entries

### Documented & Explained

- [x] Library Entries
- [x] Library Entry Logs
- [x] Library Events
- [x] List Imports

**Comment by JasonLighthunter** [comment]
will start to work on library entry logs

**Comment by JasonLighthunter** [comment]
will begin to work on library entries

**Comment by JasonLighthunter** [comment]
will start to work on Delete Library Entries
