### ISSUE TITLE
Question about sorting

### ISSUE THREAD

**Issue by SleepingPanda** [hummingbird-me/api-docs#42]
Hi, I may be asking a silly question, but I've tried many times on my own to get this working and can't seem to cut it.

According to [http://docs.kitsu.apiary.io/introduction/json-api/sorting](http://docs.kitsu.apiary.io/introduction/json-api/sorting) I should be able to just prepend ` -` to a parameter and my request should be sorted in descending order.

I'm trying to sort https://kitsu.io/api/edge/stats/1037745 by data.attributes.statsData.activity.updated_at in descending order. Is that possible? And if so, can you show me how?

**Comment by wopian** [comment]
It's not possible to sort nested arrays (may be a JSON-API limitation that could become part of the upcoming 1.1 version though). I.e, only direct children of `attributes` are sortable 😫

However, by default those arrays are sorted by `updatedAt` in ascending order, so you can reverse the array client side to achieve what you're after 👍

**Comment by SleepingPanda** [comment]
Oh! I understand now. Thank you for answering my newbie questions!
