### ISSUE TITLE
Characters & People

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#5]
### Data Structure

- [x] Anime Characters
- [x] Anime Productions
- [x] Anime Staff
- [x] Castings (deprecated)
- [x] Characters
- [x] Manga Characters
- [x] Manga Staff
- [x] People
- [x] Producers

#### GET

- [x] Anime Characters
- [x] Anime Productions
- [x] Anime Staff
- [x] Castings (deprecated)
- [x] Characters
- [x] Manga Characters
- [x] Manga Staff
- [x] People
- [x] Producers

### Documented & Explained

- [x] Anime Characters
- [x] Anime Productions
- [x] Anime Staff
- [x] Castings (deprecated)
- [x] Characters
- [x] Manga Characters
- [x] Manga Staff
- [x] People
- [x] Producers

**Comment by JasonLighthunter** [comment]
will begin to work on manga characters
