### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#6]
### Data Structure

- [x] Group Action Logs
- [x] Group Bans
- [x] Group Categories
- [x] Group Invites
- [x] Group Member Notes
- [x] Group Members
- [x] Group Neighbours
- [x] Group Permissions
- [x] Group Reports
- [x] Group Ticket Messages
- [x] Group Tickets
- [x] Groups
- [x] Leader Chat Messages

#### GET

- [x] Group Action Logs
- [x] Group Bans
- [x] Group Categories
- [x] Group Invites
- [x] Group Member Notes
- [x] Group Members
- [x] Group Neighbours
- [x] Group Permissions
- [x] Group Reports
- [x] Group Ticket Messages
- [x] Group Tickets
- [x] Groups
- [x] Leader Chat Messages

#### POST

- [x] Group Bans
- [x] Group Categories
- [x] Group Invites
- [x] Group Member Notes
- [x] Group Members
- [x] Group Neighbours
- [x] Group Permissions
- [x] Group Reports
- [x] Group Ticket Messages
- [x] Group Tickets
- [x] Groups
- [x] Leader Chat Messages

#### PATCH

- [x] Group Categories
- [x] Group Member Notes
- [x] Group Permissions
- [x] Groups

#### DELETE

- [x] Group Bans
- [x] Group Categories
- [x] Group Invites
- [x] Group Member Notes
- [x] Group Members
- [x] Group Neighbours
- [x] Group Permissions
- [x] Groups

### Documented & Explained

- [x] Group Action Logs
- [x] Group Bans
- [x] Group Categories
- [x] Group Invites
- [x] Group Member Notes
- [x] Group Members
- [x] Group Neighbours
- [x] Group Permissions
- [x] Group Reports
- [x] Group Ticket Messages
- [x] Group Tickets
- [x] Groups
- [x] Leader Chat Messages

**Comment by JasonLighthunter** [comment]
will work on group permissions

**Comment by JasonLighthunter** [comment]
will begin to work on Group Neighbors

**Comment by JasonLighthunter** [comment]
will begin to work on Group
