### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#7]
### Data Structure

- [x] Anime
- [x] Categories
- [x] Category Favorites
- [ ] Category Recommendations
- [ ] Chapters
- [ ] Drama
- [x] Episodes
- [x] Franchises *
- [x] Genres (deprecated)
- [x] Installments *
- [x] Manga
- [x] Mappings
- [ ] Media Attribute Votes
- [ ] Media Attributes
- [x] Media Follows
- [x] Media Relationships **
- [x] Streamers
- [x] Streaming Links
- [ ] Trending Anime (`/trending/anime`)
- [ ] Trending Drama
- [ ] Trending Manga

#### GET

- [x] Anime
- [x] Categories
- [x] Category Favorites
- [ ] Category Recommendations
- [ ] Chapters
- [ ] Drama
- [x] Episodes
- [x] Franchises *
- [x] Genres (deprecated)
- [x] Installments *
- [x] Manga
- [x] Mappings
- [ ] Media Attribute Votes
- [ ] Media Attributes
- [x] Media Follows
- [x] Media Relationships **
- [x] Streamers
- [x] Streaming Links
- [ ] Trending Anime (`/trending/anime`)
- [ ] Trending Drama
- [ ] Trending Manga

#### POST

- [ ] Category Favorites
- [ ] Media Attribute Votes
- [ ] Media Follows

#### PATCH

- [ ] Category Favorites
- [ ] Media Attribute Votes
- [ ] Media Follows

#### DELETE

- [ ] Category Favorites
- [ ] Media Attribute Votes
- [ ] Media Follows

### Documented & Explained

- [ ] Anime
- [ ] Categories
- [ ] Category Favorites
- [ ] Category Recommendations
- [ ] Chapters
- [ ] Drama
- [ ] Episodes
- [ ] Franchises *
- [ ] Genres (deprecated)
- [ ] Installments *
- [ ] Manga
- [ ] Mappings
- [ ] Media Attribute Votes
- [ ] Media Attributes
- [ ] Media Follows
- [ ] Media Reaction Votes
- [ ] Media Reactions
- [ ] Media Relationships **
- [ ] Streamers
- [ ] Streaming Links
- [ ] Trending Anime (`/trending/anime`)
- [ ] Trending Drama
- [ ] Trending Manga

\* Currently deprecated - use Media Relationships
** Will be deprecated in the future and reverted back to using Franchises/Installments

**Comment by JasonLighthunter** [comment]
Will now begin to work on Installments

**Comment by JasonLighthunter** [comment]
will now begin to work on streamers

**Comment by JasonLighthunter** [comment]
will now begin to work on streaming Links

**Comment by JasonLighthunter** [comment]
wil begin to work on category favorites

**Comment by JasonLighthunter** [comment]
will begin to work on media follows

**Comment by kazzarin** [comment]
This is pretty much done.
