### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#8]
### Data Structure

- [x] Comment Likes
- [x] Comments
- [x] Post Likes
- [x] Post Follows
- [x] Posts
- [x] Reports

#### GET

- [x] Comment Likes
- [x] Comments
- [x] Post Likes
- [x] Post Follows
- [x] Posts
- [x] Reports

#### POST

- [x] Comment Likes
- [x] Comments
- [x] Post Likes
- [x] Post Follows
- [x] Posts
- [x] Reports

#### PATCH

- [x] Comment Likes
- [x] Comments
- [x] Post Likes
- [x] Post Follows
- [x] Posts

#### DELETE

- [x] Comment Likes
- [x] Comments
- [x] Post Likes
- [x] Post Follows
- [x] Posts

### Documented & Explained

- [x] Comment Likes
- [x] Comments
- [x] Post Likes
- [x] Post Follows
- [x] Posts
- [x] Reports

**Comment by JasonLighthunter** [comment]
will start to work on Posts

**Comment by JasonLighthunter** [comment]
will start to work on Post Likes

**Comment by JasonLighthunter** [comment]
will start to work on Comments

**Comment by JasonLighthunter** [comment]
will begin to work on post follows

**Comment by kazzarin** [comment]
I think this can be closed, unless I missed something.
