### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/api-docs#9]
Reviews is deprecated, use Reactions

### Data Structure

- [x] Media Reaction Votes
- [x] Media Reactions
- [x] Review Likes
- [x] Reviews

#### GET

- [x] Media Reaction Votes
- [x] Media Reactions
- [x] Review Likes
- [x] Reviews

#### POST

- [x] Media Reaction Votes
- [x] Media Reactions
- [x] Review Likes
- [x] Reviews

#### PATCH

- [x] Media Reaction Votes
- [x] Media Reactions
- [x] Review Likes
- [x] Reviews

#### DELETE

- [x] Media Reaction Votes
- [x] Media Reactions
- [x] Review Likes
- [x] Reviews

### Documented & Explained

- [x] Media Reaction Votes
- [x] Media Reactions
- [x] Review Likes
- [x] Reviews

**Comment by JasonLighthunter** [comment]
will now begin to work on reviews

**Comment by JasonLighthunter** [comment]
will now begin to work on reviews likes
